services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"

  stun:
    image: coturn/coturn:alpine
    ports:
      - "49152-65535:49152-65535/udp"
      - "5349:5349/udp"
      - "5349:5349"
      - "3478:3478"

  nuxt:
    build: .
